version: '3'

services:
  proxy:
    image: traefik:raclette-alpine
    command: --logLevel="DEBUG" --entryPoints="Name:http Address::80"
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml

  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock #--logo httpmachin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/data:/data
    networks:
      - webgateway
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:portainer.localhost"
      - "traefik.port=9000"
      - "traefik.docker.network=webgateway"


networks:
  webgateway:
    driver: bridge
